Integrate our own schwifty fork
LN-Zap/schwifty-cli pull request #1
Opened 2024-04-17 11:16 UTC by Cogax

2024-04-17 12:07 UTC, mrfelton requested changes

2024-04-17 12:07 UTC, mrfelton commented on requirements.txt
> +schwifty @ git+https://github.com/LN-Zap/schwifty@main
Lets reference a specific ref / commit hash so that we have better reproducibility.

2024-04-17 12:10 UTC, Cogax commented on requirements.txt
> +schwifty @ git+https://github.com/LN-Zap/schwifty@main
https://github.com/LN-Zap/schwifty-cli/pull/1/commits/7b7d41660e7f0757c22467bb020dc016b90bc678

2024-04-17 12:26 UTC, Cogax commented
We may don't need to merge it if https://github.com/mdomke/schwifty/pull/193 gets merged soon

2024-04-18 07:21 UTC, mrfelton approved these changes

2024-04-18 07:21 UTC, merged